package ForkJoin;



import java.util.List;
import java.util.concurrent.ForkJoinPool;
import java.util.concurrent.TimeUnit;
 
public class CopyOfDriveClass
{
   public static void main(String[] args)
   {
      //Create ForkJoinPool using the default constructor.
      ForkJoinPool pool = new ForkJoinPool();
      //Create three FolderProcessor tasks. Initialize each one with a different folder path.
      CopyOfFolderProcessor system = new CopyOfFolderProcessor("D:\\workspace", "js");
     
      pool.execute(system);
     
      pool.shutdown();
      //Write the number of results generated by each task to the console.
      List<String> results;
      results =system.join(); 
      System.out.println(results);
   }
}
